In [1]:
import torch

In [3]:
from __future__ import print_function

In [4]:
x=torch.zeros(5,3, dtype=torch.long)
print (x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x=torch.tensor([5.5,3])
print (x)

tensor([5.5000, 3.0000])


In [8]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x, dtype=torch.float)
print (x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1559,  0.5063,  0.3840],
        [-0.0519,  0.4264,  1.9005],
        [ 0.0098, -0.5461,  0.6638],
        [ 0.0576, -0.3509,  0.5164],
        [-0.6515, -0.1571,  1.2775]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 0.1621,  0.7601,  1.2977],
        [ 0.3859,  0.5373,  2.8630],
        [ 0.7805,  0.3013,  0.7294],
        [ 0.9940, -0.3401,  0.7400],
        [ 0.2720,  0.8212,  1.5057]])


In [11]:
print(torch.add(x,y))

tensor([[ 0.1621,  0.7601,  1.2977],
        [ 0.3859,  0.5373,  2.8630],
        [ 0.7805,  0.3013,  0.7294],
        [ 0.9940, -0.3401,  0.7400],
        [ 0.2720,  0.8212,  1.5057]])


In [12]:
result=torch.empty(5,3)
torch.add(x,y, out=result)
print (result)

tensor([[ 0.1621,  0.7601,  1.2977],
        [ 0.3859,  0.5373,  2.8630],
        [ 0.7805,  0.3013,  0.7294],
        [ 0.9940, -0.3401,  0.7400],
        [ 0.2720,  0.8212,  1.5057]])


In [13]:
y.add_(x)
print (y)

tensor([[ 0.1621,  0.7601,  1.2977],
        [ 0.3859,  0.5373,  2.8630],
        [ 0.7805,  0.3013,  0.7294],
        [ 0.9940, -0.3401,  0.7400],
        [ 0.2720,  0.8212,  1.5057]])


In [15]:
print(x[:,1])

tensor([ 0.5063,  0.4264, -0.5461, -0.3509, -0.1571])


In [16]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x=torch.randn(1)
print(x)
print (x.item())

tensor([0.6432])
0.6431945562362671


In [22]:
a=torch.ones(5)
print (a)

tensor([1., 1., 1., 1., 1.])


In [23]:
b=a.numpy()
print (b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [33]:
if torch.cuda.is_available():
    print ("yes")
else:
    print ("nah")

nah


In [35]:
x=torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [39]:
print(y.grad_fn)

In [40]:
z=y*y*3
out=z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [42]:
a=torch.randn(2,2)
a=((a*3/(a-1)))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [43]:
out.backward()

In [44]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [45]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [48]:
x=torch.randn(3, requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print (y)

tensor([-447.4782, -670.8420,  894.3669], grad_fn=<MulBackward0>)


In [51]:
v=torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
with toch.no_grad():
    print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [55]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
